
name: asas
version: 1.4.4+10
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  cupertino_icons: ^1.0.2
  flutter_svg: #  flutter_svg: ^1.1.1+1
  reactive_forms: ^10.6.6
  permission_handler:
  bot_toast: ^4.0.3
  chopper: ^7.0.9
  logger: ^1.1.0
  get:
  cached_network_image: #cached_network_image: ^3.2.1
  shimmer: ^2.0.0
  intl_phone_field:
    git: https://github.com/l00ai/intl_phone_field.git
  smooth_page_indicator: ^1.0.0+2
  flutter_rating_bar: ^4.0.0
  custom_searchable_dropdown: ^2.1.1
  sms_autofill: ^2.2.0
  dropdown_button2: #  dropdown_button2: ^1.6.3
  flutter_widget_from_html_core: any
  fwfh_webview:
  url_launcher:
  google_maps_flutter: ^2.1.3
  location:


  intl: ^0.17.0
  image_picker:
  flutter_html: any
  youtube_player_flutter:  #  youtube_player_flutter: ^8.1.0

#  flutter_facebook_auth:
  firebase_core: ^2.14.0
  firebase_messaging:
  awesome_notifications:
#  google_sign_in:
  shared_preferences: ^2.0.15


  flutter: 
    sdk: flutter
  firebase_auth:
  flutter_datetime_picker_plus: ^2.0.1
  change_app_package_name: ^1.1.0
  http:
  custom_info_window: ^1.0.1
  clippy_flutter: ^2.0.0-nullsafety.1

dev_dependencies: 
  flutter_lints:
  lints:
  build_runner: ^2.1.4
  chopper_generator:

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/svg/owner/


  fonts:
    - family: JF
      fonts:
        - asset: assets/fonts/JF-Flat-Regular.ttf
          weight: 400
        - asset: assets/fonts/JF-Flat-bold.ttf
          weight: 700
